version: "3.6"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: bench
      MONGO_INITDB_ROOT_PASSWORD: bench
  
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bench
      ME_CONFIG_MONGODB_ADMINPASSWORD: bench