version: "3.6"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: bench
      POSTGRES_PASSWORD: bench
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
